server {
    listen 80;
    server_name cuantrack.zvy.my.id www.cuantrack.zvy.my.id;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://tflow_api:6969;
    }
}